### ISSUE TITLE
Repo update and thanks

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#75] opened 2020-03-02 14:25 UTC
@nyoung30 @pkbullock @veronicageek @pealmasa @PatD @tom-daly @juliemturner @SusanHanley @joannecklein @hugoabernier @eemancini

As the premier set of contributors to this repo, @vesajuvonen and I truly thank you! (He didn't say to include him, but I know how he feels.) We're about to launch the docs.microsoft.com version of the repo, and we couldn't have gotten to this point without you! The docs folks have been impressed with our progress, and I believe we can continue to impress them.

Of course, impressing the docs folks isn't the goal. We want to add value for the community in a way Microsoft has not tried in the past - at least in this form. We'd like to see if we can get some more activity flowing, so here are some steps we'd like to take.

## Clean up assigned issues
@nyoung30 @ScottShearer @PatD @pkbullock 

Each of you has at least one open issue assigned to you - generally because you asked to be assigned. Could you each please check the issues you have assigned to you and add a comment saying:

1. You'll commit to writing something in the next few weeks
2. You think the issue is no longer important - and why
3. Indicate that you'd like us to assign someone else

Once we get your feedback, we'll start promoting the unassigned issues to get more community traction.

## Review the articles you've written for freshness and validity
Nothing stays constant in this world, and there may have been changes since you wrote your articles. If you could take a pass through them to see if you still consider them valid, that would be great. We will undoubtedly set up a more rigorous review cycle in the future, but we'd like to be sure we have content with veracity for the launch.

## Generate new article suggestions
Have other ideas you'd like to add? Totally cool, even if you can't take them on yourself.

Thanks again for all your work and help!!! Stay tuned!

**Comment by sympmarc** [comment] 2020-03-02 14:57
Sorry - I missed @jimmyhang.

cc: @pamgreen-msft @traya1 @dstrome

**Comment by sympmarc** [comment] 2020-03-02 15:19
And I also missed some important things!

We'll be reorganizing the repo today to both adhere to some standards for the docs connection as well as to make the content flatter (are folders bad?).

- The [README](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/README.md) has been updated with the new name and logo for the effort: **Microsoft 365 Community Docs**.
- The articles will live in a folder called **Community** - no article subfolders.
- The TOC will still display the articles with the same groupings. The flat article structure gives us more options to include content in multiple places (potentially) based on tags.
- Images will move into a subfolder beneath that called **media**, with the existing subfolders containing the images for each article.
- I'll add the various M365CommunityDocs logo options to the **media** subfolder once it's in place.
- We'll be using the hashtag [#M365CommunityDocs](https://twitter.com/search?q=%23M365CommunityDocs) rather than [#SPUsageDocs](https://twitter.com/search?q=%23SPUsageDocs) going forward. This better reflects what the content is (not just SP) and where it lives.
- We will have a new markdown template for articles. 
- We will pare down your credits at the bottom of the articles to indicate you're the **Original Author**, but not the other links. This is due to standards in the docs arena. Hopefully this won't cause any angst.
- Sometime soon (this is up to @vesajuvonen) we will start some type of public exposure for the repo. Each of you - as "charter contributors" - will get public credit for your great work so far.

If I've missed anything, Microsoft folks, please comment.

**Comment by veronicageek** [comment] 2020-03-02 15:22
Due to the name change (to M365) I was wondering if articles would expand in topics and you confirmed that 🙂

Thanks
Veronique

Veronique
________________________________

**Comment by nyoung30** [comment] 2020-03-03 01:54
This is great news, I am proud to have been a part of it and am looking forward to contributing more in the future.

I've added comments to open issues assigned to me. 

Thanks @sympmarc!

Norm

**Comment by sympmarc** [comment] 2020-03-05 16:04
I think most of the reorganization is complete. Thanks to those of you who have replied back about the issues assigned to you. Time to move forward!

**Comment by joannecklein** [comment] 2020-03-05 16:07
Hi Marc, i haven’t had a chance to go in and ensure the content is up to date but i plan on doing that this weekend.

Thanks for all you’ve done on this initiative!

Joanne K

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sympmarc** [comment] 2020-03-05 16:08
@joannecklein - we're just getting started! Thanks for doing the review...

**Comment by pkbullock** [comment] 2020-03-05 16:09
I’ll do the same Marc go in over the weekend, been working hard on the modernisation tooling this slipped my mind. Sorry.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sympmarc** [comment] 2020-03-14 23:45
Adding @bigpix2000, as he just offereed to help with #13...

Another suggestion to you folks: you may be getting some public credit for your work here in the near future. Please make sure your Github profiles reflect who you really are: name, photo, location, company (if you want), etc. We want people to know who you are!

**Comment by bigpix2000** [comment] 2020-03-14 23:47
So many profiles so many places ... thanks for the reminder ... added to my tasks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pealmasa** [comment] 2020-03-15 10:13
Hi Marc,

I have collaborated on this article
https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/list-column-or-site-column-which-one-to-choose.md
but I don't see my name on it.

cheers

**Comment by sympmarc** [comment] 2020-03-15 18:31
@pealmasa  Looking at that article history, I don't see any changes from you. Are you sure that's the right one? I'm hoping we didn't lose any attribution when we moved things from sp-usage-docs to this new repo.

**Comment by pealmasa** [comment] 2020-03-15 22:33
I believe we did lose. I've added the search related part of the list vs
site column.
No worries, I expect to contribute more as time allows me.

**Comment by sympmarc** [comment] 2020-03-16 13:01
Over the weekend, I did some reorganizing. If any of you have a chance, take a look at the revised [TOC](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/TOC.md). I think this broader structure will give us more room to grow.

@pealmasa I'm really sorry that detail disappeared. No worries, though. The fact that you are involved in this discussion means we know you are one of the early contributors. You'll get credit!

cc: @JoanneHendrickson

**Comment by JimmyHang** [comment] 2020-03-16 13:37
#wow, it's super awesome love it, ;)

**Comment by bigpix2000** [comment] 2020-03-16 14:04
@sympmarc , let me know what you recommend I do for the article created for licensing (issue #13 )  I just recalled that there was going to be an MD template for articles after I created mine. Thanks in advance!

**Closed** 2020-08-18 02:28 UTC
Labels: discussion
